### ISSUE TITLE
[JOSS Review] - Test functionality

### ISSUE THREAD

**Issue by GregaVrbancic** [nedRad88/SCALAR#4]
Hi @nedRad88, as required by openjournals/joss-reviews/issues/2676 checklist could you provide some automatic tests or manual steps, so that the functionality of the software can be verified.

**Comment by xiaohk** [comment]
Second this. Thanks!

**Comment by nedRad88** [comment]
Hi @GregaVrbancic , @xiaohk , I have followed the suggestion from @atanikan and created a kind of bloated version of the software so the testing the functionality is much easier now. I have updated installation instructions and README file. So, please follow the new instructions to install and run the test competition using our software. Thanks!

**Comment by galessiorob** [comment]
👋 @GregaVrbancic @xiaohk 

Checking in on this requirement, could you please go over the expanded testing and install instructions and close this issue if you two are satisfied with the changes?

Thanks!
