### ISSUE TITLE
[JOSS Review] - Documentation

### ISSUE THREAD

**Issue by GregaVrbancic** [nedRad88/SCALAR#5]
Hi @nedRad88, could you provide some documentation for main API functionalities as required by openjournals/joss-reviews/issues/2676 revision?

**Comment by xiaohk** [comment]
I found a [documentation](https://github.com/nedRad88/SCALAR/blob/master/SCALAR_Quick_Start_Guide.pdf) for the competition participants.

**Comment by nedRad88** [comment]
Hi @GregaVrbancic,

The documentation has been updated, and also [README.md](https://github.com/nedRad88/SCALAR/blob/master/README.md), saying more about the main API functionalities. 
@xiaohk What you sharedm it is a [Tutorial](https://github.com/nedRad88/SCALAR/blob/master/SCALAR_Quick_Start_Guide.pdf) on how to use a platform. It provides the information how to set up the competition but also how to participate in one. We will soon provide a simpler procedure to do this and test the functionality of the platform.

**Comment by GregaVrbancic** [comment]
Hi @nedRad88, could you provide me a link to the api documentation? Inam having trouble to find it.

**Comment by nedRad88** [comment]
Hi @GregaVrbancic, the documentation is available at https://nedrad88.github.io/scalarDocs.github.io/
I will update the installation instructions next and update the information about the documentation on the repository.

**Comment by GregaVrbancic** [comment]
@nedRad88 Thanks. Great work on documentation!

**Comment by nedRad88** [comment]
Thanks! I will close this issue then.
