### ISSUE TITLE
[JOSS Review] - Community guidelines

### ISSUE THREAD

**Issue by GregaVrbancic** [nedRad88/SCALAR#6]
Hi @nedRad88, could you please provide community guidelines, how the community could contribute to this project. This issue references to the review issue openjournals/joss-reviews/issues/2676.

Here are some examples of community guidelines of popular open-source projects:

- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/rails/rails/blob/master/CONTRIBUTING.md
- https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

**Comment by nedRad88** [comment]
Hi @GregaVrbancic,

the repository has been updated with [contributing.md](https://github.com/nedRad88/SCALAR/blob/master/CONTRIBUTING.md) and the [pull request template](https://github.com/nedRad88/SCALAR/blob/master/pull_request_template.md).

**Comment by GregaVrbancic** [comment]
Hi @nedRad88, this looks good to me.
